# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pyProject\SuperLabelTool\Form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 653)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 995, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar_action = QtWidgets.QToolBar(MainWindow)
        self.toolBar_action.setObjectName("toolBar_action")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_action)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.dockSetting = QtWidgets.QDockWidget(MainWindow)
        self.dockSetting.setAcceptDrops(True)
        self.dockSetting.setObjectName("dockSetting")
        self.dockWidgetLabel = QtWidgets.QWidget()
        self.dockWidgetLabel.setObjectName("dockWidgetLabel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetLabel)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetLabel)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_0)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_label = QtWidgets.QTableWidget(self.tab_0)
        self.tableWidget_label.setObjectName("tableWidget_label")
        self.tableWidget_label.setColumnCount(0)
        self.tableWidget_label.setRowCount(0)
        self.gridLayout_7.addWidget(self.tableWidget_label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_type = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_type.setObjectName("groupBox_type")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_type)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioRect = QtWidgets.QRadioButton(self.groupBox_type)
        self.radioRect.setObjectName("radioRect")
        self.gridLayout_5.addWidget(self.radioRect, 0, 1, 1, 1)
        self.radioCircle = QtWidgets.QRadioButton(self.groupBox_type)
        self.radioCircle.setObjectName("radioCircle")
        self.gridLayout_5.addWidget(self.radioCircle, 0, 4, 1, 1)
        self.radioPoint = QtWidgets.QRadioButton(self.groupBox_type)
        self.radioPoint.setObjectName("radioPoint")
        self.gridLayout_5.addWidget(self.radioPoint, 0, 3, 1, 1)
        self.radioPolygon = QtWidgets.QRadioButton(self.groupBox_type)
        self.radioPolygon.setObjectName("radioPolygon")
        self.gridLayout_5.addWidget(self.radioPolygon, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_type, 1, 0, 1, 1)
        self.groupBox_label = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_label.setObjectName("groupBox_label")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_label)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_label = QtWidgets.QLineEdit(self.groupBox_label)
        self.lineEdit_label.setObjectName("lineEdit_label")
        self.gridLayout_4.addWidget(self.lineEdit_label, 0, 0, 1, 1)
        self.pushButton_label = QtWidgets.QPushButton(self.groupBox_label)
        self.pushButton_label.setObjectName("pushButton_label")
        self.gridLayout_4.addWidget(self.pushButton_label, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_label, 3, 0, 1, 1)
        self.groupBox_editer = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_editer.setObjectName("groupBox_editer")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_editer)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_editer = QtWidgets.QLineEdit(self.groupBox_editer)
        self.lineEdit_editer.setObjectName("lineEdit_editer")
        self.gridLayout_9.addWidget(self.lineEdit_editer, 0, 0, 1, 1)
        self.pushButton_editer = QtWidgets.QPushButton(self.groupBox_editer)
        self.pushButton_editer.setObjectName("pushButton_editer")
        self.gridLayout_9.addWidget(self.pushButton_editer, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_editer, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.dockSetting.setWidget(self.dockWidgetLabel)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockSetting)
        self.dockFilelist = QtWidgets.QDockWidget(MainWindow)
        self.dockFilelist.setEnabled(True)
        self.dockFilelist.setAcceptDrops(True)
        self.dockFilelist.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dockFilelist.setFloating(False)
        self.dockFilelist.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockFilelist.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockFilelist.setObjectName("dockFilelist")
        self.dockWidgetImage = QtWidgets.QWidget()
        self.dockWidgetImage.setObjectName("dockWidgetImage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetImage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_image = QtWidgets.QTableWidget(self.dockWidgetImage)
        self.tableWidget_image.setObjectName("tableWidget_image")
        self.tableWidget_image.setColumnCount(0)
        self.tableWidget_image.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_image, 0, 0, 1, 1)
        self.dockFilelist.setWidget(self.dockWidgetImage)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockFilelist)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/open_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_Dir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/open_dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Dir.setIcon(icon1)
        self.actionOpen_Dir.setObjectName("actionOpen_Dir")
        self.actionOpen_Anno = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/open_anno.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Anno.setIcon(icon2)
        self.actionOpen_Anno.setObjectName("actionOpen_Anno")
        self.actionOpen_Annotation_Dir = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/open_anno_dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Annotation_Dir.setIcon(icon3)
        self.actionOpen_Annotation_Dir.setObjectName("actionOpen_Annotation_Dir")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon5)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon6)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon7)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNext = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon8)
        self.actionNext.setObjectName("actionNext")
        self.actionPrev = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev.setIcon(icon9)
        self.actionPrev.setObjectName("actionPrev")
        self.actionCreate_RectBox = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_RectBox.setIcon(icon10)
        self.actionCreate_RectBox.setObjectName("actionCreate_RectBox")
        self.actionEdit_RectBox = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/edit_select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_RectBox.setIcon(icon11)
        self.actionEdit_RectBox.setObjectName("actionEdit_RectBox")
        self.actionEdit_Label = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/edit_label.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Label.setIcon(icon12)
        self.actionEdit_Label.setObjectName("actionEdit_Label")
        self.actionShow_RectBox = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_RectBox.setIcon(icon13)
        self.actionShow_RectBox.setObjectName("actionShow_RectBox")
        self.actionHidden_RectBox = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHidden_RectBox.setIcon(icon14)
        self.actionHidden_RectBox.setObjectName("actionHidden_RectBox")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon15)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon16)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon17)
        self.actionZoom.setObjectName("actionZoom")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTutorial.setIcon(icon18)
        self.actionTutorial.setObjectName("actionTutorial")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Dir)
        self.menuFile.addAction(self.actionOpen_Annotation_Dir)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionNext)
        self.menuEdit.addAction(self.actionPrev)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCreate_RectBox)
        self.menuEdit.addAction(self.actionEdit_RectBox)
        self.menuEdit.addAction(self.actionEdit_Label)
        self.menuView.addAction(self.actionShow_RectBox)
        self.menuView.addAction(self.actionHidden_RectBox)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addAction(self.actionZoom)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar_action.addAction(self.actionOpen)
        self.toolBar_action.addAction(self.actionOpen_Dir)
        self.toolBar_action.addAction(self.actionOpen_Annotation_Dir)
        self.toolBar_action.addAction(self.actionSave)
        self.toolBar_action.addSeparator()
        self.toolBar_action.addAction(self.actionNext)
        self.toolBar_action.addAction(self.actionPrev)
        self.toolBar_action.addAction(self.actionZoomIn)
        self.toolBar_action.addAction(self.actionZoomOut)
        self.toolBar_action.addAction(self.actionZoom)
        self.toolBar_action.addSeparator()
        self.toolBar_action.addAction(self.actionCreate_RectBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.actionClose.triggered.connect(self.graphicsView.invalidateScene)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar_action.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockSetting.setWindowTitle(_translate("MainWindow", "Label Setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "Labels"))
        self.groupBox_type.setTitle(_translate("MainWindow", "Label Type---[None]"))
        self.radioRect.setText(_translate("MainWindow", "Rect"))
        self.radioCircle.setText(_translate("MainWindow", "Circle"))
        self.radioPoint.setText(_translate("MainWindow", "Point"))
        self.radioPolygon.setText(_translate("MainWindow", "Poly"))
        self.groupBox_label.setTitle(_translate("MainWindow", "Default Label---[None]"))
        self.pushButton_label.setText(_translate("MainWindow", "Set"))
        self.groupBox_editer.setTitle(_translate("MainWindow", "Editer---[None]"))
        self.pushButton_editer.setText(_translate("MainWindow", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Setting"))
        self.dockFilelist.setWindowTitle(_translate("MainWindow", "File List - [E:/]"))
        self.actionOpen.setText(_translate("MainWindow", "Open Image"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen_Dir.setText(_translate("MainWindow", "Open Image Dir"))
        self.actionOpen_Dir.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionOpen_Anno.setText(_translate("MainWindow", "Open Annotation"))
        self.actionOpen_Anno.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionOpen_Annotation_Dir.setText(_translate("MainWindow", "Open Annotation Dir"))
        self.actionOpen_Annotation_Dir.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionNext.setText(_translate("MainWindow", "Next Image"))
        self.actionNext.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionPrev.setText(_translate("MainWindow", "Prev Image"))
        self.actionPrev.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionCreate_RectBox.setText(_translate("MainWindow", "Create RectBox"))
        self.actionEdit_RectBox.setText(_translate("MainWindow", "Edit RectBox"))
        self.actionEdit_Label.setText(_translate("MainWindow", "Edit Label"))
        self.actionShow_RectBox.setText(_translate("MainWindow", "Show RectBox"))
        self.actionHidden_RectBox.setText(_translate("MainWindow", "Hide RectBox"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom.setText(_translate("MainWindow", "Original Size"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))

import res_rc
