# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pyProject\SuperLabelTool_OCR\Form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 589)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dragon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_10.addWidget(self.graphicsView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 995, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar_action = QtWidgets.QToolBar(MainWindow)
        self.toolBar_action.setObjectName("toolBar_action")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_action)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.dockFilelist = QtWidgets.QDockWidget(MainWindow)
        self.dockFilelist.setEnabled(True)
        self.dockFilelist.setAcceptDrops(True)
        self.dockFilelist.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dockFilelist.setFloating(False)
        self.dockFilelist.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockFilelist.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockFilelist.setObjectName("dockFilelist")
        self.dockWidgetImage = QtWidgets.QWidget()
        self.dockWidgetImage.setObjectName("dockWidgetImage")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetImage)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetImage)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.treeWidget_file = QtWidgets.QTreeWidget(self.tab)
        self.treeWidget_file.setObjectName("treeWidget_file")
        self.gridLayout_6.addWidget(self.treeWidget_file, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_7.addWidget(self.textEdit, 1, 0, 1, 2)
        self.radioButton_det = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_det.setObjectName("radioButton_det")
        self.gridLayout_7.addWidget(self.radioButton_det, 0, 0, 1, 1)
        self.radioButton_word = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_word.setObjectName("radioButton_word")
        self.gridLayout_7.addWidget(self.radioButton_word, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_rescale = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_rescale.setEnabled(False)
        self.radioButton_rescale.setObjectName("radioButton_rescale")
        self.gridLayout_3.addWidget(self.radioButton_rescale, 1, 2, 1, 1)
        self.checkBox_resize = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_resize.setObjectName("checkBox_resize")
        self.gridLayout_3.addWidget(self.checkBox_resize, 0, 0, 1, 1)
        self.radioButton_refixed = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_refixed.setEnabled(False)
        self.radioButton_refixed.setObjectName("radioButton_refixed")
        self.gridLayout_3.addWidget(self.radioButton_refixed, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.doubleSpinBox_rw = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_rw.setEnabled(False)
        self.doubleSpinBox_rw.setDecimals(1)
        self.doubleSpinBox_rw.setMaximum(10000.0)
        self.doubleSpinBox_rw.setObjectName("doubleSpinBox_rw")
        self.gridLayout_3.addWidget(self.doubleSpinBox_rw, 2, 2, 1, 2)
        self.doubleSpinBox_rh = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_rh.setEnabled(False)
        self.doubleSpinBox_rh.setDecimals(1)
        self.doubleSpinBox_rh.setMaximum(10000.0)
        self.doubleSpinBox_rh.setObjectName("doubleSpinBox_rh")
        self.gridLayout_3.addWidget(self.doubleSpinBox_rh, 5, 2, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetImage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.dockFilelist.setWidget(self.dockWidgetImage)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockFilelist)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 2, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_4.addWidget(self.pushButton_1, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 0, 0, 1, 3)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 3, 0, 1, 1)
        self.pushButton_detect = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_detect.setObjectName("pushButton_detect")
        self.gridLayout_4.addWidget(self.pushButton_detect, 3, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/open_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_Dir = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/open_dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Dir.setIcon(icon2)
        self.actionOpen_Dir.setObjectName("actionOpen_Dir")
        self.actionOpen_Anno = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/open_anno.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Anno.setIcon(icon3)
        self.actionOpen_Anno.setObjectName("actionOpen_Anno")
        self.actionOpen_Annotation_Dir = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/open_anno_dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Annotation_Dir.setIcon(icon4)
        self.actionOpen_Annotation_Dir.setObjectName("actionOpen_Annotation_Dir")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon6)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon7)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon8)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNext = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon9)
        self.actionNext.setObjectName("actionNext")
        self.actionPrev = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev.setIcon(icon10)
        self.actionPrev.setObjectName("actionPrev")
        self.actionCreate_RectBox = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_RectBox.setIcon(icon11)
        self.actionCreate_RectBox.setObjectName("actionCreate_RectBox")
        self.actionEdit_RectBox = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/edit_select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_RectBox.setIcon(icon12)
        self.actionEdit_RectBox.setObjectName("actionEdit_RectBox")
        self.actionEdit_Label = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/edit_label.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Label.setIcon(icon13)
        self.actionEdit_Label.setObjectName("actionEdit_Label")
        self.actionShow_RectBox = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_RectBox.setIcon(icon14)
        self.actionShow_RectBox.setObjectName("actionShow_RectBox")
        self.actionHidden_RectBox = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHidden_RectBox.setIcon(icon15)
        self.actionHidden_RectBox.setObjectName("actionHidden_RectBox")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon16)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon17)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon18)
        self.actionZoom.setObjectName("actionZoom")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTutorial.setIcon(icon19)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionSet_Voc_Root = QtWidgets.QAction(MainWindow)
        self.actionSet_Voc_Root.setObjectName("actionSet_Voc_Root")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Dir)
        self.menuFile.addAction(self.actionOpen_Annotation_Dir)
        self.menuFile.addAction(self.actionSet_Voc_Root)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionNext)
        self.menuEdit.addAction(self.actionPrev)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCreate_RectBox)
        self.menuEdit.addAction(self.actionEdit_RectBox)
        self.menuEdit.addAction(self.actionEdit_Label)
        self.menuView.addAction(self.actionShow_RectBox)
        self.menuView.addAction(self.actionHidden_RectBox)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addAction(self.actionZoom)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar_action.addAction(self.actionOpen)
        self.toolBar_action.addAction(self.actionOpen_Dir)
        self.toolBar_action.addAction(self.actionOpen_Annotation_Dir)
        self.toolBar_action.addAction(self.actionSave)
        self.toolBar_action.addSeparator()
        self.toolBar_action.addAction(self.actionNext)
        self.toolBar_action.addAction(self.actionPrev)
        self.toolBar_action.addAction(self.actionZoomIn)
        self.toolBar_action.addAction(self.actionZoomOut)
        self.toolBar_action.addAction(self.actionZoom)
        self.toolBar_action.addSeparator()
        self.toolBar_action.addAction(self.actionCreate_RectBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SuperLabelTool-[Picture]"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar_action.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockFilelist.setWindowTitle(_translate("MainWindow", "File List - [E:/]"))
        self.treeWidget_file.headerItem().setText(0, _translate("MainWindow", "File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "File"))
        self.radioButton_det.setText(_translate("MainWindow", "detect"))
        self.radioButton_word.setText(_translate("MainWindow", "word"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "OCR"))
        self.groupBox_3.setTitle(_translate("MainWindow", "RESIZE"))
        self.radioButton_rescale.setText(_translate("MainWindow", "scale"))
        self.checkBox_resize.setText(_translate("MainWindow", "ON"))
        self.radioButton_refixed.setText(_translate("MainWindow", "fixed"))
        self.label_3.setText(_translate("MainWindow", "Pixel"))
        self.label_2.setText(_translate("MainWindow", "height"))
        self.label.setText(_translate("MainWindow", "width"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Advanced"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Editor"))
        self.pushButton_2.setText(_translate("MainWindow", "OK"))
        self.groupBox.setTitle(_translate("MainWindow", "Text"))
        self.pushButton.setText(_translate("MainWindow", "Next"))
        self.pushButton_1.setText(_translate("MainWindow", "Prev"))
        self.pushButton_4.setText(_translate("MainWindow", "Save"))
        self.checkBox.setText(_translate("MainWindow", "AUTO OCR"))
        self.pushButton_detect.setText(_translate("MainWindow", "detect"))
        self.actionOpen.setText(_translate("MainWindow", "Open Image"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen_Dir.setText(_translate("MainWindow", "Open Image Dir"))
        self.actionOpen_Dir.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionOpen_Anno.setText(_translate("MainWindow", "Open Annotation"))
        self.actionOpen_Anno.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionOpen_Annotation_Dir.setText(_translate("MainWindow", "Open Annotation Dir"))
        self.actionOpen_Annotation_Dir.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionNext.setText(_translate("MainWindow", "Next Image"))
        self.actionNext.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionPrev.setText(_translate("MainWindow", "Prev Image"))
        self.actionPrev.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionCreate_RectBox.setText(_translate("MainWindow", "Create RectBox"))
        self.actionEdit_RectBox.setText(_translate("MainWindow", "Edit RectBox"))
        self.actionEdit_Label.setText(_translate("MainWindow", "Edit Label"))
        self.actionShow_RectBox.setText(_translate("MainWindow", "Show RectBox"))
        self.actionHidden_RectBox.setText(_translate("MainWindow", "Hide RectBox"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom.setText(_translate("MainWindow", "Original Size"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))
        self.actionSet_Voc_Root.setText(_translate("MainWindow", "Set Pascale Voc Root"))

import res_rc
