# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\seeta-xpc\Desktop\SuperLabelTool\Form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 449)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 621, 401))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 745, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/open_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_Dir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/open_dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Dir.setIcon(icon1)
        self.actionOpen_Dir.setObjectName("actionOpen_Dir")
        self.actionOpen_Anno = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/open_anno.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Anno.setIcon(icon2)
        self.actionOpen_Anno.setObjectName("actionOpen_Anno")
        self.actionOpen_Annotation_Dir = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/open_anno_dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Annotation_Dir.setIcon(icon3)
        self.actionOpen_Annotation_Dir.setObjectName("actionOpen_Annotation_Dir")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon5)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon6)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon7)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNext_Image = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext_Image.setIcon(icon8)
        self.actionNext_Image.setObjectName("actionNext_Image")
        self.actionPrev_Image = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev_Image.setIcon(icon9)
        self.actionPrev_Image.setObjectName("actionPrev_Image")
        self.actionCreate_RectBox = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_RectBox.setIcon(icon10)
        self.actionCreate_RectBox.setObjectName("actionCreate_RectBox")
        self.actionEdit_RectBox = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/edit_select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_RectBox.setIcon(icon11)
        self.actionEdit_RectBox.setObjectName("actionEdit_RectBox")
        self.actionEdit_Label = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/edit_label.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Label.setIcon(icon12)
        self.actionEdit_Label.setObjectName("actionEdit_Label")
        self.actionShow_RectBox = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_RectBox.setIcon(icon13)
        self.actionShow_RectBox.setObjectName("actionShow_RectBox")
        self.actionHidden_RectBox = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHidden_RectBox.setIcon(icon14)
        self.actionHidden_RectBox.setObjectName("actionHidden_RectBox")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_in.setIcon(icon15)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon16)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionOriginal_Size = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOriginal_Size.setIcon(icon17)
        self.actionOriginal_Size.setObjectName("actionOriginal_Size")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTutorial.setIcon(icon18)
        self.actionTutorial.setObjectName("actionTutorial")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Dir)
        self.menuFile.addAction(self.actionOpen_Anno)
        self.menuFile.addAction(self.actionOpen_Annotation_Dir)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionNext_Image)
        self.menuEdit.addAction(self.actionPrev_Image)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCreate_RectBox)
        self.menuEdit.addAction(self.actionEdit_RectBox)
        self.menuEdit.addAction(self.actionEdit_Label)
        self.menuView.addAction(self.actionShow_RectBox)
        self.menuView.addAction(self.actionHidden_RectBox)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_Out)
        self.menuView.addAction(self.actionOriginal_Size)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionOpen_Dir)
        self.toolBar.addAction(self.actionOpen_Anno)
        self.toolBar.addAction(self.actionOpen_Annotation_Dir)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNext_Image)
        self.toolBar.addAction(self.actionPrev_Image)
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_Out)
        self.toolBar.addAction(self.actionOriginal_Size)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreate_RectBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open Image"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen_Dir.setText(_translate("MainWindow", "Open Image Dir"))
        self.actionOpen_Dir.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionOpen_Anno.setText(_translate("MainWindow", "Open Annotation"))
        self.actionOpen_Anno.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionOpen_Annotation_Dir.setText(_translate("MainWindow", "Open Annotation Dir"))
        self.actionOpen_Annotation_Dir.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionNext_Image.setText(_translate("MainWindow", "Next Image"))
        self.actionNext_Image.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionPrev_Image.setText(_translate("MainWindow", "Prev Image"))
        self.actionPrev_Image.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionCreate_RectBox.setText(_translate("MainWindow", "Create RectBox"))
        self.actionEdit_RectBox.setText(_translate("MainWindow", "Edit RectBox"))
        self.actionEdit_Label.setText(_translate("MainWindow", "Edit Label"))
        self.actionShow_RectBox.setText(_translate("MainWindow", "Show RectBox"))
        self.actionHidden_RectBox.setText(_translate("MainWindow", "Hide RectBox"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionOriginal_Size.setText(_translate("MainWindow", "Original Size"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

